import Link from "next/link";
import { ArrowLeft, Download, LockKeyhole, ShieldCheck } from "lucide-react";
import { notFound } from "next/navigation";
import { requireAdmin, getApplication } from "@/server/admin";
import { ApplicationStatusForm } from "@/components/application-status-form";

export const dynamic = "force-dynamic";
const kindLabels: Record<string, string> = { idFront: "Government-issued ID — front", idBack: "Government-issued ID — back", resume: "CV / Resume", taxDocument: "W-2 or 1099" };

export default async function DetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAdmin(); const { id } = await params; const application = await getApplication(session.userId, id); if (!application) notFound();
  return <div className="admin-shell"><header className="admin-header"><Link href="/admin" className="brand"><span className="brand-symbol"><ShieldCheck size={20} /></span><span>WorkHire<span className="brand-light">Desk</span><span className="brand-dot">.</span></span></Link><span className="staff-label"><ShieldCheck size={14} /> Staff portal</span></header><section className="admin-content detail"><Link href="/admin" className="back-button"><ArrowLeft size={16} /> All applications</Link><div className="detail-heading"><div><span className="eyebrow"><span /> {application.reference_code}</span><h1>{application.first_name} {application.last_name}</h1><p>Submitted {new Intl.DateTimeFormat("en-US", { dateStyle: "long", timeStyle: "short" }).format(new Date(application.created_at))}</p></div><ApplicationStatusForm applicationId={application.id} initialStatus={application.status} /></div><div className="admin-alert"><LockKeyhole size={18} /><p><strong>SSN is not displayed in the staff portal.</strong> Access requires a separately authorized, audited workflow that is not enabled in this release.</p></div><div className="detail-grid"><section className="detail-card"><h2>Contact information</h2><dl><div><dt>Email</dt><dd>{application.email}</dd></div><div><dt>Phone</dt><dd>{application.phone}</dd></div><div><dt>Date of birth</dt><dd>{application.date_of_birth}</dd></div><div className="full"><dt>Residential address</dt><dd>{application.address}</dd></div></dl></section><section className="detail-card"><h2>Employment information</h2><dl><div><dt>Position desired</dt><dd>{application.position_desired}</dd></div><div><dt>Previous employer</dt><dd>{application.previous_employer}</dd></div><div className="full"><dt>Privacy consent</dt><dd>Accepted {new Intl.DateTimeFormat("en-US", { dateStyle: "medium" }).format(new Date(application.consent_timestamp))}</dd></div></dl></section><section className="detail-card documents"><h2>Documents</h2><p className="card-intro">Only clean files can be downloaded. Each download is authorized server-side, logged, and uses a 60-second link.</p><ul>{application.documents.map(document => <li key={document.kind}><span>{kindLabels[document.kind] ?? document.kind}</span><span className="document-action"><span className={`scan scan-${document.scan_status}`}>{document.scan_status}</span>{document.scan_status === "clean" && <a className="document-download" href={`/api/admin/applications/${application.id}/documents/${document.kind}`}><Download size={13} /> Download</a>}</span></li>)}</ul>{!application.documents.length && <p>No documents were recorded.</p>}</section></div></section></div>;
}
