import { test, expect } from '@playwright/test';
import { createCipheriv,randomBytes } from 'node:crypto';
const id='11111111-1111-4111-8111-111111111111';
test('authorized applicant detail, notifications, and transient SSN reveal',async({page,context})=>{
 const nonce=randomBytes(12),cipher=createCipheriv('aes-256-gcm',Buffer.alloc(32,9),nonce);
 const encrypted=Buffer.concat([cipher.update(JSON.stringify({userId:'22222222-2222-4222-8222-222222222222',accessToken:'synthetic-access-token',expiresAt:Date.now()+600000})),cipher.final()]);
 const value=[nonce,cipher.getAuthTag(),encrypted].map(p=>p.toString('base64url')).join('.');
 await context.addCookies([{name:'whd_admin',value,url:'http://localhost:4320',httpOnly:true,sameSite:'Strict'}]);
 await page.goto(`/admin/applications/${id}`);
 await expect(page.getByRole('heading',{name:'Synthetic Applicant'})).toBeVisible();
 await expect(page.getByText('•••-••-6789')).toBeVisible();
 await expect(page.getByText(/Validated files are available only/)).toBeVisible();
 await expect(page.getByRole('link',{name:'Download'})).toHaveCount(4);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 page.once('dialog',d=>d.dismiss());
 await page.getByRole('button',{name:'Reveal SSN'}).click();
 await expect(page.getByText('123-45-6789')).toHaveCount(0);
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Reveal SSN'}).click();
 await expect(page.getByText('123-45-6789')).toBeVisible();
 await page.getByRole('button',{name:'Hide',exact:true}).click();
 await expect(page.getByText('123-45-6789')).toHaveCount(0);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Reveal SSN'}).click();
 await expect(page.getByText('123-45-6789')).toBeVisible();
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 await expect(page.getByText('123-45-6789')).toHaveCount(0);
 expect(await page.evaluate(()=>localStorage.length+sessionStorage.length)).toBe(0);
 await page.clock.install();
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Reveal SSN'}).click();
 await expect(page.getByText('123-45-6789')).toBeVisible();
 await page.clock.fastForward(31000);
 await expect(page.getByText('123-45-6789')).toHaveCount(0);
 const front=await context.request.get(`/api/admin/applications/${id}/documents/idFront`,{maxRedirects:0});expect(front.status()).toBe(307);
 const download=await context.request.get(`/api/admin/applications/${id}/documents/resume`,{maxRedirects:0});expect(download.status()).toBe(307);expect(download.headers()['cache-control']).toContain('no-store');
 const r=await context.request.post(`/api/admin/applications/${id}/ssn`,{headers:{origin:'http://localhost:4320','x-confirm-ssn-reveal':'true'}});
 expect(r.status()).toBe(200);expect(r.headers()['cache-control']).toContain('no-store');
 const denied=await context.request.post(`/api/admin/applications/${id}/ssn`,{headers:{origin:'https://foreign.example','x-confirm-ssn-reveal':'true'}});expect(denied.status()).toBe(403);
 await page.getByLabel(/Notifications,/).click();
 await expect(page.locator('.notification-panel')).toContainText('Synthetic Applicant');
 await page.getByRole('button',{name:'Mark all as read'}).click();
 await expect(page.getByLabel('Notifications, 0 unread')).toBeVisible();
 await page.reload();await expect(page.getByLabel('Notifications, 0 unread')).toBeVisible();
 await context.clearCookies();
 const unauth=await context.request.post(`/api/admin/applications/${id}/ssn`,{headers:{origin:'http://localhost:4320','x-confirm-ssn-reveal':'true'}});expect(unauth.status()).toBe(403);
});
